#!/usr/bin/env bash
# Configure a new Ubuntu machine
# Install nginx listening on port 80
# Return a page containing 'Hello World' string

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
