#!/usr/bin/env bash
# Configure Nginx so that its HTTP response
# contains a custom header

# Update the package lists for upgrades and new
# package installations
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Add to the nginx configuration file an error 404 page
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo "Hello world!" > /var/www/html/index.html
echo "Cesi n'est pas une page" > /var/www/html/404.html

server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://youtube.com permanent;
        }
        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
}"

echo "$server_config" > /etc/nginx/sites-enabled/default

# If the configuration test is successful, reload Nginx to apply the changes
sudo service nginx restart
