#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

sudo apt-get update -y
sudo apt-get uograde -y
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get install -y haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
HOSTNAME=$(hostname)
echo "
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 527906-web-01 100.27.4.132:80 check
    server 527906-web-02 54.90.12.140:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
