#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y haproxy=1.6.\*
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
HOSTNAME=$(hostname)
echo "
frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 527906-web-01 184.72.121.49:80 check
    server 527906-web-02 54.90.12.140:80 check
" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
