#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

apt-get update -y
apt-get upgrade -y
apt-get install -y haproxy=1.6.\*
systemctl enable haproxy
HOSTNAME=$(hostname)
echo "
frontend joshkimtech.tech
    bind 0:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 527906-web-01 184.72.121.49:80 check
    server 527906-web-02 54.90.12.140:80 check
" >> /etc/haproxy/haproxy.cfg

service restart haproxy
