#!/usr/bin/env bash
# Generate a MYSQL dump and creates compressed archive out of it
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
filename="$day-$month-$year.tar.gz"

mysqldump -u root --password="$1" --all-databases > backup.sql
tar -zcvf "$filename" backup.sql
