#!/usr/bin/env bash
# This script displays numbers 1 - 100 in list format
# and displays "FizzBuzz" when number is multiple of 3
# and 5, "Fizz" for multiples of 3, "Buzz" for multiples
# 5, otherwise display the number.
for i in {1..100}
do
if (( i % 15 == 0 ))
	then
	echo "FizzBuzz"
elif (( i % 3 == 0 ))
	then
	echo "Fizz"
elif (( i % 5 == 0 ))
	then
	echo "Buzz"
else
	echo "$i"
fi
done
