#!/usr/bin/env bash
# This is a script is a loop from 1 - 10 displaying
# "Best School" for other iterations, "bad luck" for
# the 4th iteration and "good luck" for the 8th using
# a while loop and if, elif, and else statements
count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
