#!/usr/bin/env bash
# Script displaays numbers from 1 - 20 with "bad luck
# from Japan" in 4th iteration, "bad luck from Italy"
# in the 8th and "bad luck from China" in the 17th using
# a while loop and case statement.
count=1
while [ $count -le 20 ]
do
	case $count in
		4)
			echo "$count bad luck from China"
			;;
		9)
			echo "$count bad luck from Japan"
			;;
		17)
			echo "$count bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	count=$((count+1))
done
