#!/usr/bin/env bash
# This is a script that displays time for 12 hrs
# and 59 mins using a while loop
hour="0"
while [ $hour -le 12 ]
do
echo "Hour: $hour"
minute="1"
while [ $minute -le 59 ]
do
echo "$minute"
minute=$((minute+1))
done
hour=$((hour+1))
done
