#!/usr/bin/env bash
# Configure Ubuntu server with the following requirements:
# Localhost resolves to 127.0.0.2 from 127.0.0.1
# facebook.com resolves to 8.8.8.8 from 102.132.100.35

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
